# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  release:
    types: # This configuration does not affect the page_build event above
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Xcode Select
      # You may pin to the exact commit or the version.
        uses: devbotsxyz/xcode-select@v1.1.0
        with:
        # Version to use (like '11.7', '12' or simply 'latest')
          version: 'latest'
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: xcodebuild -version

      - name: Test Script
        run: sh ./test.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          xcodebuild -version
          mktemp -d -t mbox
          echo Add other actions to build,
          echo test, and deploy your project.
